baseURL: https://vrfaria-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website by Victor Rios Faria
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I am an LBS MBA2024 candidate, originally from Brazil. Management consultant background, data science enthusiast. In my free time, I love to cook, travel, and play board games.
    title: Hi, my name is Victor
  blog: {}
  contact:
    address:
      - city: London
        country: UK
#        street: Street
#        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: vriosfaria.mba2024@london.edu
        title: Email
    enable: yes
#    phone:
#      - phone: (000) 000-0000 x1234
#        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
 #       label: Twitter
  #      url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/victor.riosfaria
#      - icon: fa-instagram
 #       label: Instagram
  #      url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/vrfaria/dsb_victor
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/vrfaria/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: child.jpg
        subtitle: Nice to meet you!
        title: About Me
        url: blogs/about_me
      - image: travel.jpeg
        subtitle: Meeting cultures and places
        title: Travelling
        url: blogs/travel
      - image: azul.jpg
        subtitle: Friends and Fun
        title: Board Games
        url: blogs/board_games
      - image: Gradus.jpeg
        subtitle: Engineer + Consultant + Data
        title: My Career So Far
        url: blogs/career
      - image: rstudio.png
        subtitle: The challenges of learning R
        title: Data Science for Business at LBS
        url: blogs/dsfb
      - image: datascience.avif
        subtitle: Why not both?
        title: R or Alteryx?
        url: blogs/r_alteryx
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I hope you enjoyed this blog"
    title: At√© breve!
    url: blogs
